config/routes.rb
Rails.application.routes.draw do
  get 'my_restaurants/index', as: 'my_restaurants'
  devise_for :admins
  resources :restaurants do
    resources :dishes
  end

  resources :dishes do
    resources :items
  end

  root 'restaurants#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :restaurant
  has_many :items
  validates :dish_group, :name, :description, :price, :photo, :restaurant_id,
  					presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :dish
  validates :name, :calories, :dish_id, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :restaurant
  validates :date, :sub_total, :taxes, :total, :restaurant_id,
  					presence: true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :dishes, dependent: :destroy
	has_many :orders, dependent: :destroy
	belongs_to :admin
	validates :name, :description, :address, :phone, :logo, presence: true

	mount_uploader :logo, LogoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
	before_action :load_restaurant, except: :destroy
	before_action :find_restaurant_dish, only: [:show, :edit, :update]
	before_action :authenticate_admin!, except: :show

	def index
		@dishes = @restaurant.dishes
	end

	def show
		total_calories
	end

	def edit
	end

	def new
		@dish = @restaurant.dishes.build
	end

	def create
		@dish = @restaurant.dishes.build(dish_params)

		if @dish.save
			redirect_to(@restaurant, notice: 'Dish created successfully!')
		else
			render 'restaurants/show'
		end
	end

	def update
		if @dish.update(dish_params)
			redirect_to(restaurant_dish_path(@restaurant, @dish), notice: 'Dish updated successfully!')
		else
			render :edit
		end
	end

	def destroy
		@dish = Dish.find(params[:id])
		@restaurant = Restaurant.find(@dish.restaurant_id)
		@dish.destroy
		redirect_to(@restaurant, alert: 'Dish destroyed!')
	end

	private

	def find_restaurant_dish
		@dish = @restaurant.dishes.find(params[:id])
	end

	def load_restaurant
		@restaurant = Restaurant.find(params[:restaurant_id])
	end

	def dish_params
		params.require(:dish).permit(:dish_group, :name, :description, :price, :photo)
	end

	def total_calories
		@total_calories = 0
		@dish.items.each do |item|
			@total_calories = @total_calories + item.calories
		end
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :load_dish
	before_action :authenticate_admin!

	def index
		@items = @dish.items
	end

	def show
		@item = @dish.items.find(params[:id])
	end

	def edit
		@item = @dish.items.find(params[:id])
	end

	def new
		@item = @dish.items.new
	end

	def create
		@item = @dish.items.build(item_params)

		if @item.save
			redirect_to(restaurant_dish_path(@dish.restaurant_id, @dish), notice: 'Item created successfully!')
		else
			render :new
		end
	end

	def update
		@item = @dish.items.find(params[:id])

		if @item.update(item_params)
			redirect_to(restaurant_dish_path(@dish.restaurant_id, @dish), notice: 'Item updated successfully!')
		else
			render :edit
		end
	end

	def destroy
		@item = @dish.items.find(params[:id])
		@item.destroy
		redirect_to(restaurant_dish_path(@dish.restaurant_id, @dish), alert: 'Item destroyed!')
	end

	private

	def load_dish
		@dish = Dish.find(params[:dish_id])
	end

	def item_params
		params.require(:item).permit(:name, :calories)
	end
end

app/controllers/my_restaurants_controller.rb
class MyRestaurantsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@my_restaurants = Restaurant.where(admin: current_admin)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin!, except: [:index, :show]

	def index
		@restaurants = Restaurant.all
	end

	def show
	end

	def edit
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = current_admin.restaurants.build(restaurant_params)
		@restaurant.admin_id = current_admin.id

		if @restaurant.save
			redirect_to(my_restaurants_path, notice: 'Restaurant created successfully!')
		else
			render :new
		end
	end

	def update
		@restaurant.admin = current_admin
		if @restaurant.update(restaurant_params)
			redirect_to(my_restaurants_path, notice: 'Restaurant updated correctly!')
		else
			render :edit
		end
	end

	def destroy
		@restaurant.destroy
		redirect_to(my_restaurants_path, notice: 'Restaurant destroyed!')
	end

	private

	def find_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

	def restaurant_params
		params.require(:restaurant).permit(:name, :description, :address, :phone, :logo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/my_restaurants_helper.rb
module MyRestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dishes/_form.html.erb
<div class="container">
<%= form_for([@restaurant, @dish], html: { multipart: true } ) do |f| %>

	<% if @dish.errors.any? %>
		<ul>
			<% @dish.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="form-group">
		<%= f.label :dish_group %>
		<%= f.text_field :dish_group, class: 'form-control' %>
  </div>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :price %>
		<%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :photo %>
		<%= f.file_field :photo, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<div class="container">
	<h1>Edit Dish</h1>

	<%= render 'form' %>

	<%= link_to 'Back', restaurant_path(@restaurant), class: 'btn btn-danger' %>
</div>

app/views/dishes/new.html.erb
<div class="container">
	<h1>New Dish</h1>

	<%= render 'form' %>

	<%= link_to 'Back', restaurant_path(@restaurant), class: 'btn btn-danger' %>
</div>

app/views/dishes/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="thumbnail">
				<%= image_tag(@dish.photo.medium) %>
				<div class="caption">
					<h1><%= @dish.name %></h1>
					<p><%= number_to_currency(@dish.price) %></p>
					<% if admin_signed_in? %>
						<%= link_to 'New Item', new_dish_item_path(@dish, @item), class: 'btn btn-success' %>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-md-8">
			<% if @dish.items.empty? %>
				<p>No ingredients added yet!</p>
			<% else %>
				<table class='table'>
					<thead>
						<tr>
							<td>Ingredient</td>
							<td>Calories</td>
							<% if admin_signed_in? %>
							<td>Edit</td>
							<td>Destroy</td>
							<% end %>
						</tr>
					</thead>
					<tbody>
					<% @dish.items.each do |item| %>
						<tr>
							<td><%= item.name %></td>
							<td><%= item.calories %></td>
							<% if admin_signed_in? %>
								<td><%= link_to 'Edit', edit_dish_item_path(@dish, item) %></td>
								<td><%= link_to('Destroy', dish_item_path(@dish, item), method: :delete,
																data: { confirm: 'Are you sure?' }) %></td>
							<% end %>
						</tr>
					<% end %>
					<hr>
						<tr>
							<td>Total Calories</td>
							<td>
								<strong><%= @total_calories %></strong>
							</td>
							<td></td>
							<td></td>
						</tr>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8">
			<%= link_to 'Back', restaurant_path(@dish.restaurant_id), class: 'btn btn-danger' %>
		</div>
	</div>
</div>

app/views/items/_form.html.erb
<div class="container">
<%= form_for([@dish, @item]) do |f| %>

	<% if @item.errors.any? %>
		<ul>
			<% @item.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
  </div>

	<div class="form-group">
		<%= f.label :calories %>
		<%= f.text_field :calories, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
	<h1>Edit Item</h1>

	<%= render 'form' %>

	<%= link_to 'Back', restaurant_dish_path(@dish.restaurant_id, @dish), class: 'btn btn-danger' %>
</div>

app/views/items/new.html.erb
<div class="container">
	<h1>New Item</h1>

	<%= render 'form' %>

	<%= link_to 'Back', restaurant_dish_path(@dish.restaurant_id, @dish), class: 'btn btn-danger' %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
	<div id="notice-wrapper">
		<%= render 'layouts/messages' %>
	</div>
<%= render partial: 'shared/navbar' %>

<%= yield %>

</body>
</html>

app/views/my_restaurants/index.html.erb
<div class="container">
	<% if admin_signed_in? %>
	<%= link_to('New Restaurant', new_restaurant_path, class: 'btn btn-success') %>
	<% end %>

	<% if @my_restaurants.empty? %>
		<h2>No Restaurants have been added yet!</h2>
	<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>Logo</th>
					<th>Name</th>
					<th>Description</th>
					<th>Address</th>
					<th>Phone</th>
					<% if admin_signed_in? %>
					<th>Edit</th>
					<th>Destroy</th>
					<% end %>
				</tr>
			</thead>
			<tbody>
				<% @my_restaurants.each do |restaurant| %>
					<tr>
						<td><%= link_to(image_tag(restaurant.logo.thumb), restaurant) %></td>
						<td><%= restaurant.name %></td>
						<td><%= restaurant.description %></td>
						<td><%= restaurant.address %></td>
						<td><%= restaurant.phone %></td>
						<% if admin_signed_in? %>
						<td><%= link_to('Edit', edit_restaurant_path(restaurant)) %></td>
						<td><%= link_to('Destroy', restaurant, method: :delete,
														data: { confirm: 'Are you sure?' }) %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>

</div>

app/views/restaurants/_form.html.erb
<div class="container">
<%= form_for(@restaurant, html: { multipart: true }) do |f| %>

	<% if @restaurant.errors.any? %>
		<ul>
			<% @restaurant.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :address %>
		<%= f.text_area :address, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :phone %>
		<%= f.text_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.label :logo %>
		<%= f.file_field :logo, class: 'form-control' %>
  </div>

  <div class="form-group">
		<%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
	<h1>Edit Restaurant</h1>

	<%= render 'form' %>

	<%= link_to 'Back', restaurants_path, class: 'btn btn-danger' %>
</div>

app/views/restaurants/index.html.erb
<div class="container">

	<% if @restaurants.empty? %>
		<h2>No Restaurants have been added yet!</h2>
	<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>Logo</th>
					<th>Name</th>
					<th>Description</th>
					<th>Address</th>
					<th>Phone</th>
				</tr>
			</thead>
			<tbody>
				<% @restaurants.each do |restaurant| %>
					<tr>
						<td><%= link_to(image_tag(restaurant.logo.thumb), restaurant) %></td>
						<td><%= restaurant.name %></td>
						<td><%= restaurant.description %></td>
						<td><%= restaurant.address %></td>
						<td><%= restaurant.phone %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>

</div>

app/views/restaurants/new.html.erb
<div class="container">
	<h1>New Restaurant</h1>

	<%= render 'form' %>

	<%= link_to 'Back', restaurants_path, class: 'btn btn-danger' %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
	<h1><%= @restaurant.name %></h1>

	<% if admin_signed_in? %>
		<%= link_to('New Dish', new_restaurant_dish_path(@restaurant), class: 'btn btn-success') %>
		<%= link_to('Back', restaurants_path, class: 'btn btn-danger') %>
	<% end %>

	<% if @restaurant.dishes.empty? %>
		<h2>No dishes available yet.</h2>
	<% else %>
		<table class="table">
			<thead>
				<tr>
					<th>Photo</th>
					<th>Group</th>
					<th>Name</th>
					<th>Description</th>
					<th>Price</th>
					<% if admin_signed_in? %>
					<th>Edit</th>
					<th>Destroy</th>
					<% end %>
				</tr>
			</thead>
			<tbody>
				<% @restaurant.dishes.each do |dish| %>
					<tr>
						<td><%= link_to(image_tag(dish.photo.food_thumb), restaurant_dish_path(@restaurant, dish)) %></td>
						<td><%= dish.dish_group %></td>
						<td><%= dish.name %></td>
						<td><%= dish.description %></td>
						<td><%= number_to_currency(dish.price) %></td>
						<% if admin_signed_in? %>
						<td><%= link_to('Edit', edit_restaurant_dish_path(@restaurant, dish)) %></td>
						<td><%= link_to('Destroy', dish, method: :delete,
														data: { confirm: 'Are you sure?' }) %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
</div>

app/views/shared/_dropdown.html.erb
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_admin.email %><span class="caret"></span></a>
	<ul class="dropdown-menu">
		<%= render 'shared/registration_items' %>
		<%= render 'shared/nav_items' %>
		<%= render 'shared/login_items' %>
	</ul>
</li>

app/views/shared/_login_items.html.erb
<% if admin_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_admin_session_path)  %>
  </li>
<% end %>

app/views/shared/_nav_items.html.erb
<% if admin_signed_in? %>
  <li>
  <%= link_to('My Restaurants', my_restaurants_path) %>
  </li>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('Resto', restaurants_path, class: 'navbar-brand') %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <%= render partial: 'shared/dropdown' %>
        <% else %>
          <%= render partial: 'shared/login_items' %>
          <%= render partial: 'shared/registration_items' %>
        <% end %>

<!--         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_registration_items.html.erb
<% if admin_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_admin_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_admin_registration_path)  %>
  </li>
<% end %>